version: '2'
services:
  dbpg:
    image: 'postgres:12.1-alpine'
    networks:
      - bridgenet
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=123456
    volumes:
      - "./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      - "./database/script:/script"
      - "./database/data:/var/lib/postgresql/data"

  restapi:
    image: 'chriswei/restapi:0.0.1'
    networks: 
      - bridgenet
    ports:
      - '3000:3000'
    depends_on:
      - dbpg

  frontend:
    image: 'chriswei/frontend:0.0.1'
    networks: 
      - bridgenet
    ports:
      - '80:80'
    depends_on:
      - restapi
      
networks:
  bridgenet:
