# db-backup-cronjob.yaml
# https://zh.wikipedia.org/wiki/Cron

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: db-backup-cron
spec:
#  schedule: "0 */2 * * *"
  schedule: "* * * * *"
  suspend: false
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          volumes:
          - name: backup
            hostPath:
              path: "/root/projects/dockerimages/database/backup"
          containers:
          - name: db-backup-job-container
            image: postgres:12.1-alpine
            imagePullPolicy: IfNotPresent
            command: ["bin/bash", "/backup/backup.sh"]
            volumeMounts:
            - name: backup
              mountPath: "/backup"
            env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: all-secret
                  key: password_db
