# echo -n '<plaintext-of-secret>' | base64
# <hash-of-secret>
# echo '<hash-of-secret>' | base64 --decode
# <plaintext-of-secret>

# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: all-secret
type: Opaque
data:
  password_db: MTIzNDU2
